import "~/styles/globals.css";

import { AppSidebar } from "./_components/app-sidebar";
import AuthButton from "./_components/AuthButton";
import { Button } from "@/components/ui/button";
import ClientProvider from "./_components/ClientProvider";
import { ConnectKitButton } from "connectkit";
import Header from "./_components/Header";
import { Inter } from "next/font/google";
import Link from "next/link";
import { SidebarInset } from "./_components/ui/sidebar";
import { TRPCReactProvider } from "~/trpc/react";
import { Toaster } from "./_components/ui/toaster";

const inter = Inter({
  subsets: ["latin"],
  variable: "--font-sans",
});

export const metadata = {
  title: "Create T3 App",
  description: "Generated by create-t3-app",
  icons: [{ rel: "icon", url: "/favicon.ico" }],
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body
        className={`font-sans ${inter.variable} flex min-h-screen flex-1 flex-col bg-slate-50`}
      >
        <ClientProvider>
          <TRPCReactProvider>
            {/* <AppSidebar /> */}
            {/* <SidebarInset className="overflow-hidden"> */}

            <main className=" flex flex-1 flex-col">
              {/* <Header /> */}
              {children}
            </main>
            {/* </SidebarInset> */}
            <Toaster />
          </TRPCReactProvider>
        </ClientProvider>
      </body>
    </html>
  );
}
